### ISSUE TITLE
Edit transaction: crash when clicking Enter button

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/CapitalBe#54]
It crashes and the transaction gets deleted apparently.
The report:

[CapitalBe-3054-debug-15-05-2024-15-50-46.report.txt](https://github.com/HaikuArchives/CapitalBe/files/15324067/CapitalBe-3054-debug-15-05-2024-15-50-46.report.txt)

**Comment by dospuntos** [comment]
I spent some time creating and deleting transactions and accounts. It seems like this bug happens when trying to edit a transaction from an account with only one transaction. As soon as there's two or more transactions, any of them can be edited.

So it's an edge case, but still something that should be solved.

**Comment by humdingerb** [comment]
Yep. I see that, too. Good hunting! :)
